#!/usr/bin/env python3
"""Regenerate the pinned Go reference's locale-independent simple case mappings."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
EXPORTER = r'''package main
import ("crypto/sha256"; "encoding/binary"; "encoding/hex"; "encoding/json"; "os"; "unicode")
func main() {
 tables := map[string][][2]uint32{}
 sum := sha256.New()
 var bytes [8]byte
 for r := rune(0); r <= unicode.MaxRune; r++ {
  upper, lower := unicode.ToUpper(r), unicode.ToLower(r)
  if upper != r { tables["upper"] = append(tables["upper"], [2]uint32{uint32(r), uint32(upper)}) }
  if lower != r { tables["lower"] = append(tables["lower"], [2]uint32{uint32(r), uint32(lower)}) }
  binary.LittleEndian.PutUint32(bytes[:4], uint32(upper))
  binary.LittleEndian.PutUint32(bytes[4:], uint32(lower))
  sum.Write(bytes[:])
 }
 json.NewEncoder(os.Stdout).Encode(struct {Version string; Tables map[string][][2]uint32; Digest string}{unicode.Version, tables, hex.EncodeToString(sum.Sum(nil))})
}'''


def render(data):
    if data['Version'] != '17.0.0':
        raise ValueError('review Unicode version changes with the reference pin')
    digest = hashlib.sha256()
    maps = {name: dict(rows) for name, rows in data['Tables'].items()}
    for point in range(0x110000):
        digest.update(struct.pack('<II', maps['upper'].get(point, point), maps['lower'].get(point, point)))
    if digest.hexdigest() != data['Digest']:
        raise ValueError('mapping tables differ from Go Unicode functions')
    lines = ['import { QbeOutput, qbe_output_line } from qbe_output', '',
             '# Generated by tools/unicode-case-data.py; do not edit by hand.',
             '# Go Unicode 17.0.0 simple mappings; no locale, expansion or context rules.',
             'def emit_unicode_case_data(mut output: QbeOutput)']
    for name in ('upper', 'lower'):
        rows = data['Tables'][name]
        assert rows == sorted(rows) and len(rows) == len(maps[name])
        values = ', '.join(f'w {source}, w {target}' for source, target in rows)
        il = f'data $trbn_case_{name} = align 4 {{ {values} }}\n'
        il += f'data $trbn_case_{name}_count = align 8 {{ l {len(rows)} }}'
        lines.append('\tqbe_output_line(output, ' + json.dumps(il) + ')')
    return '\n'.join(lines + ['end', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--go', default='go')
    parser.add_argument('--evidence', type=Path)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix='case-unicode-') as temporary:
        source = Path(temporary) / 'main.go'
        source.write_text(EXPORTER)
        result = subprocess.run([args.go, 'run', source], check=True, capture_output=True,
                                text=True, env=dict(os.environ, GOWORK='off'), timeout=60)
    data = json.loads(result.stdout)
    text = render(data)
    target = ROOT / 'compiler/src/unicode_case_data.trb'
    if args.check:
        if target.read_text() != text:
            raise ValueError('Unicode case data differs from the current Go toolchain')
    else:
        target.write_text(text)
    if args.evidence:
        args.evidence.write_text(json.dumps(data) + '\n')
    print(f"Unicode {data['Version']}: all 1,114,112 code points agree with Go case mappings")


if __name__ == '__main__':
    main()
