#!/usr/bin/env python3
"""Regenerate compact Unicode identifier properties from the reference Go toolchain."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
EXPORTER = r'''package main
import ("crypto/sha256"; "encoding/hex"; "encoding/json"; "os"; "unicode")
func main() {
 tables := map[string]*unicode.RangeTable{"letter": unicode.L, "digit": unicode.Nd, "upper": unicode.Upper}
 data := map[string][][3]uint32{}
 for name, table := range tables {
  for _, r := range table.R16 { data[name] = append(data[name], [3]uint32{uint32(r.Lo), uint32(r.Hi), uint32(r.Stride)}) }
  for _, r := range table.R32 { data[name] = append(data[name], [3]uint32{r.Lo, r.Hi, r.Stride}) }
 }
 sum := sha256.New()
 for r := rune(0); r <= unicode.MaxRune; r++ {
  var flags byte
  if unicode.IsLetter(r) { flags |= 1 }; if unicode.IsDigit(r) { flags |= 2 }; if unicode.IsUpper(r) { flags |= 4 }
  sum.Write([]byte{flags})
 }
 json.NewEncoder(os.Stdout).Encode(struct {Version string; Tables map[string][][3]uint32; Digest string}{unicode.Version, data, hex.EncodeToString(sum.Sum(nil))})
}'''


def render(data):
    lines = ["# Generated by tools/unicode-identifier-data.py; do not edit by hand.",
             f"# Go Unicode {data['Version']}: Letter, Decimal_Number and Uppercase_Letter.",
             "# Each ordered range stores six hexadecimal digits for low, high and stride.", ""]
    for name in ('letter', 'digit', 'upper'):
        rows = data['Tables'][name]
        previous = -1
        for low, high, stride in rows:
            if not (previous < low <= high <= 0x10ffff and 0 < stride <= 0xffffff):
                raise ValueError(f"invalid {name} range: {(low, high, stride)}")
            previous = high
        encoded = ''.join(f'{value:06x}' for row in rows for value in row)
        lines += [f'def unicode_identifier_{name}_data(): String',
                  f'\treturn "{encoded}"', 'end', '']
    # Validate every scalar classification against Go's actual public predicates,
    # including Latin-1 fast paths and unassigned code points.
    flags = bytearray(0x110000)
    for name, bit in (('letter', 1), ('digit', 2), ('upper', 4)):
        for low, high, stride in data['Tables'][name]:
            for point in range(low, high + 1, stride):
                flags[point] |= bit
    if hashlib.sha256(flags).hexdigest() != data['Digest']:
        raise ValueError('ranges differ from Go Unicode predicates')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--go', default='go')
    parser.add_argument('--evidence', type=Path)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix='identifier-unicode-') as temporary:
        source = Path(temporary) / 'main.go'
        source.write_text(EXPORTER)
        result = subprocess.run([args.go, 'run', source], check=True, capture_output=True,
                                text=True, env=dict(os.environ, GOWORK='off'), timeout=60)
    data = json.loads(result.stdout)
    text = render(data)
    target = ROOT / 'compiler/src/unicode_identifier_data.trb'
    if args.check:
        if target.read_text() != text:
            raise ValueError('Unicode identifier data differs from the current Go toolchain')
    else:
        target.write_text(text)
    if args.evidence:
        args.evidence.write_text(json.dumps(data, indent=2) + '\n')
    print(f"Unicode {data['Version']}: all 1,114,112 code points agree with Go")


if __name__ == '__main__':
    main()
